import { GetterTree } from 'vuex'

export const state = () => ({
  list: [
    {
      id: 1,
      name: 'Brand 1',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 2,
      name: 'Brand 2',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 3,
      name: 'Brand 3',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 4,
      name: 'Brand 4',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 5,
      name: 'Brand 5',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 6,
      name: 'Brand 6',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 7,
      name: 'Brand 7',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 8,
      name: 'Brand 8',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 9,
      name: 'Brand 9',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 10,
      name: 'Brand 10',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 11,
      name: 'Brand 11',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 12,
      name: 'Brand 12',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 13,
      name: 'Brand 13',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 14,
      name: 'Brand 14',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 15,
      name: 'Brand 15',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 16,
      name: 'Brand 16',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 17,
      name: 'Brand 17',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 18,
      name: 'Brand 18',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 19,
      name: 'Brand 19',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
    {
      id: 20,
      name: 'Brand 20',
      image: '~/assets/images/product.jpeg',
      category: 'electronics',
      description: 'Bla bla bla',
      price: '$200',
      quantity: 12,
      orderQuantity: 10,
    },
  ],
})

export type stateT = ReturnType<typeof state>

export const namespaced = true

export const getters: GetterTree<stateT, stateT> = {
  list(state) {
    return state.list
  },
}
